# Generated by Django 5.1 on 2024-09-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_jobpost_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobpost",
            old_name="type",
            new_name="job_type",
        ),
    ]
