# Generated by Django 5.1 on 2024-09-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Uploads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imgage", models.ImageField(upload_to="images")),
                ("description", models.CharField(max_length=100)),
            ],
        ),
    ]
