# Generated by Django 5.1 on 2024-09-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploadapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploads",
            old_name="imgage",
            new_name="image",
        ),
    ]
